modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
logoFile="reworks.png" #optional
[[mods]] #mandatory
modId="reworks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Reworks" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
credits="Credits for this mod goes to SneK152 (the mod developer)." #optional
authors="SneK152" #optional
description='''
Reworks is a massive overhaul to the game.
'''
[[dependencies.reworks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.reworks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
